-- ==========================================
-- Admin Table Creation (Root + Branch Admins)
-- ==========================================

USE Music_dept;

-- Create admin table (supports both ROOT and BRANCH admins)
CREATE TABLE IF NOT EXISTS root_admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('ROOT', 'BRANCH') NOT NULL DEFAULT 'BRANCH',
    branch VARCHAR(100) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    INDEX idx_role (role),
    INDEX idx_branch (branch)
);

-- Note: All admin passwords will be hashed using bcrypt
-- The password hash will be generated by the backend script
--
-- Default admin accounts:
-- ROOT: username='root', password='root', role='ROOT', branch=NULL
-- BRANCH: username='karmaveer', password='karmaveer', role='BRANCH', branch='Karmaveer Nagar Society'
li relaCH: username='Godoli', password='Godoli', role='BRANCH', branch='Godoli, Satara'
-- BRANCH: username='Krantismruti', password='Krantismruti', role='BRANCH', branch='Krantismruti, Satara'
-- BRANCH: username='karad', password='karad', role='BRANCH', branch='Karad'

